language: minimal

services:
  - docker

script:
  - docker build -t ${repo}/alpine-curl:latest alpine-curl
  - docker build -t ${repo}/s3fs:latest s3fs

deploy:
  - docker push ${repo}/alpine-curl:latest
  - docker push ${repo}/s3fs
