language: minimal

services:
  - docker

env:
  global:
    - secure: sjCf3zhIcocP2B7TjBMBJYDhJV5tdqPvAE3vm8SbwpCx7v8mXT0fwMMam17k2/iMwnlNWPmmjo+COryxssxdLmVHqzwNHhY2aaqGzL0FYc8KMjnuqyupZVO/IlFZhMxIcLYefLmtFEHXLmYDK/GRbXeyhhFUo6rjTPs4oJ/Cy2MW8Elew4XulAs0OJ9JJxVWljIAbbZJF3CymdChjAY11Sh+qhmxrguds1J5XU1jOsHTr9XBqjR3ngbsB97zy6qNj82ZQlEWIIrjE9SCJfqWRPGGuYgGMVlsE7Kd0ZopLYdgh+IGDTmFHZytTtE51ft0qqE4t7zuJZyQ4xwHsKrorGPFBG4OV04YkCEXtXfRMA8pyseZfwodp/qrtjtIkK/DVs8RcexT6Uwc7CECYhm2oi7rooq1MbhEp7sRkCglUhRpA4MT5lxpKaq2k1+87rY0kL85fghuPDDfVjfdc8ojSasJRdUrACmOhByhmsSGmtKWCdbl9Za2Ja0bD2R/iNQBH9D1ozeXH4KMZrTEC4PffzDIAJ/NhQBflVMdKAG1uNbknlUYxEDVhmqWsQscZ/jvNm7g/Vzo8j4xpcg4AlWccZkbDZGCbBpISbmbOW/MMjA5GKBJD4hF9SrFtt1FhJwSu5afb8ZNEJXKHgCmLn3XTC74g4rNGUQHD0Oij3s09Rc=

script:
  - docker build -t josh9398/alpine-curl:latest alpine-curl/
  - docker build -t josh9398/s3fs:latest s3fs/
  - echo $TEST
