language: minimal

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=josh9398
    - secure: "bZeZvCOS8Cy9uQQ8aF0INbuadqkLZaT1/zXbAwGkv8X4zRYTEqICG4qzgDLRJ0dLpSn4/U/7+IQhzbIFM5G4sX/c5MQeN9tsafNBn1pz/zbWjjqbsNaqBAw5YB1FcFq5Air+gOwcYNldIzB6PLv+enmp3XM5yQWEWDF3P48a6TzTs5my6sbK1wdzvGB7d+kdohBTckjFJ1OHZOjnRD2yejj5Amp/EITJbKGgZfX7cPEVfIHVzUQqmjrYhsTMtPJ7DuINhqyZ7dQnuwLp1URsyCNmKZ6ih4HfvyZtYQ5lo7yc2KqSIzxpatwLizffKRrer1+efrwUqnVpbGK7gwYBZ8i6LaTcFNEMEMqgeZqIGuk0yH3Yp+m67/Jzh42F8xnd2kcga8RhlnBaqCA+oJ7WpfBgFPx//2YBlEdOVCONL0kaPsVvLkcL13jqPmSJGUH/GfMHI9qJDi/NziFfe9d7sUthr+0mDUN04uAKu133sy1fAkfOmk5w6j7DCL1edfNoCXRYBXw9lyn4qv9VH6nkvmkfKmKdL4bXIjUUC24+bSmL6owEPFPJIZvsEHbznPUV8lDhe74UcbFkVfXLMg8eVCdUrZ9nUjGIcnDooBlq+uTGu6HZHPDxPBjTlqnxfvNYGcEQilsVyopSbHLdA2UDmOBZcfs9zDbVepygekI6ksk="

script:
  - docker build -t ${DOCKER_USERNAME}/alpine-curl:latest alpine-curl/
  - docker build -t ${DOCKER_USERNAME}/s3fs:latest s3fs/
  - docker build -t ${DOCKER_USERNAME}/jenkins:latest jenkins/
  - docker build -t ${DOCKER_USERNAME}/debug-shed:latest debug-shed/

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push ${DOCKER_USERNAME}/alpine-curl:latest
  - docker push ${DOCKER_USERNAME}/s3fs:latest
  - docker push ${DOCKER_USERNAME}/jenkins:latest
  - docker push ${DOCKER_USERNAME}/debug-shed:latest
