name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish apline-curl
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: josh9398/alpine-curl
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: alpine-curl
      - name: Publish s3fs
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: josh9398/s3fs
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: s3fs
      - name: Publish jenkins
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: josh9398/jenkins
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: jenkins
      - name: Publish debug-shed
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: josh9398/debug-shed
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: debug-shed    
